#!/bin/zsh

#this script should install the dependencies needed to run static tracker. 

#the installer assumes that miniconda or anaconda is installed because the conda command is necessary

echo "Installing TubeTracker and its dependencies..."

# 1: initiate the conda comand to be able to run the scripts

echo ""
echo ""
echo ""

echo "...Initializing conda..."
echo ""
echo ""

conda init --user --all

echo "...Done..."
echo ""
echo ""

# 2: create a virtual invironment to install the dependencies

echo ""

echo "...Creating a Virtual environment for isolation..."
echo ""
echo ""

conda create -n tt_voys_brown python=3.11.4

echo "...Done..."
echo ""
echo ""

echo ""

echo "...Installing dependencies..."

echo ""
echo ""

eval "$(conda shell.zsh activate tt_voys_brown)"

echo ""
echo ""

echo "...Installing WxPython..."

python -m pip install wxpython==4.2.1

echo "...Done..."
echo ""

echo ""

echo "...Installing OpenCV..."

#python -m pip install opencv-python==4.9.0.80
conda install conda-forge::opencv=4.10.0
echo ""

echo "...Installing Pandas..."

python -m pip install pandas==2.1.4
echo ""

echo "...Installing motpy..."

python -m pip install motpy==0.0.10
echo ""

echo "...Done..."

eval "$(conda shell.zsh deactivate)"

echo "...Installation Completed."
